### ISSUE TITLE
HOW TO RUNNING IT WITH MY OWN VIDEO?

### ISSUE THREAD

**Issue by DarrenZsx** [StrangerZhang/pyECO#12]
Hello, i am new to visual tracking, and  i have already done the demo running, 
But i don't know how to running it with my own video? what should i do?
thanks for a lot!

**Comment by StrangerZhang** [comment]
You can find a solution here[#4](https://github.com/StrangerZhang/pyECO/issues/4)

**Comment by DarrenZsx** [comment]
thanks for answering me ! I followed the instructions, and it does works on the video! 
But i got another problem: after i select a roi on the first frame of the video,  with the video plays, i found the bbox always on the same place , its size changes,but not follow the object i selected.
here is my code, and i comment the middle part, cause i found it will not work if i follow all the instructions.
#######
is_video = '.mp4' in video_dir
    if is_video:
        cam = cv2.VideoCapture(video_dir)
        ret, frame = cam.read()
        bbox = cv2.selectROI(frame)
        frames = []
        # while ret:
        #     frames.append(frame)
        #     cam = cv2.VideoCapture(video_dir)
        # ret, frame = cam.read()
        # bbox = cv2.selectROI(frame)
        # frames = []
        while ret:
            frames.append(frame)
            ret, frame = cam.read()
################
and i have already tryed to get every frame of picture(Is this necessary？)  from video, but i don't know how to get my own 'groundtruth_rect.txt', i got the roi of the obj in the first frame with labelme, and i put the roi in 'groundtruth_rect.txt' like this:584 233 239 388,(xmin, min, w, h,    #only one line), . but it don't work and got error:IndexError: single positional indexer is out-of-bounds, even if i delete all the lines except the first line of origin 'groundtruth_rect.txt', i got the same error too.
thx a lot!

**Comment by DarrenZsx** [comment]
after i comment the all the code about 'gt_bboxes.iloc[idx]', the model works on video and img, that means without  gt_box rois in 'groundtruth_rect.txt', the bbox can not move. so all the problem is how to get my own  'groundtruth_rect.txt', or is there sth wrong with model update?

**Comment by DarrenZsx** [comment]
thanks for answering me ! I followed the instructions, and it does works on the video!
But i got another problem: after i select a roi on the first frame of the video, with the video plays, i found the bbox always on the same place , its size changes a bit, but not follow the object i selected.

and i find that if we run model on our own imgs we should comment all code  about 'gt_bboxes.iloc[idx]', cause we don't have all 'groundtruth_rect.txt'.

anyway  thx a lot!
