### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by wastacat** [StrangerZhang/pyECO#3]
Sorry ,I'm s a rookie in keras & Neural network.
Pardom,can I ask you a question?

I am trying my best to make your codes runnable the whole afternoon,but unfortunatly I failed，can  you Provide a list of dependent kits?
Would you plz make the usage more detailed so that anyone interested in your work would ultimate and contribute it.

Thanks in advance : )

**Comment by StrangerZhang** [comment]
Please provide your error logs.
Have your tried setting PYTHONPATH to the pyECO directory and successfully running the demo_eco_hc.py
The requirements of this repo are
1. numpy
2. scipy
3. mxnet
4. pickle 
5. python-opencv
6. cupy
7. pyfftw
8. glob
9. pandas
10. pillow

**Comment by wastacat** [comment]
Thank you for your answer,the problem has been solved.
I use demo_ECO_hc.py, its fps 2~3.  Is this normal?
Or where do I have to set up?
Thank you again for your answer.  : )

**Comment by StrangerZhang** [comment]
Currently you are running the deep feature version, you should change pyECO/eco/config/config.py comment line 6 and remove comment in line 7 to run without deep feature, with deep feature the speed should be 6fps on a fair gpu and without deep feature, the speed should be 40~50fps or so.

**Comment by wastacat** [comment]
OK , I have changed the settings, Its fps can reach the speed you said!
Thank you for your contribution :))
