### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Tetsujinfr** [StrangerZhang/pyECO#4]
hi
first, tx for the repo.

Now when executing the demo I have the following error (the video passed is a mp4 of 6mins so about 10k frames), can you help please?

```
~/pyECO$ python bin/demo_ECO_hc.py --video_dir ~/Desktop/videos/1000FPSSlowMotion.mp4 
/home/tets/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "bin/demo_ECO_hc.py", line 66, in <module>
    main(args.video_dir)
  File "bin/demo_ECO_hc.py", line 18, in main
    height, width = frames[0].shape[:2]
IndexError: list index out of range
```

**Comment by StrangerZhang** [comment]
Currently the demo_ECO_hc.py only support OTB(object tracking benchmark) format, such as  sequences/Crossing in my repo

if your input is a video, you should change the demo_ECO_hc.py using VideoCapture, and also provide the groundtruth bounding box in first frame. Or convert your mp4 video to image files,  like sequences/Crossing in my repo

**Comment by Tetsujinfr** [comment]
Tx for pointing this out, all clear now. I will try to modify it eventually.

**Comment by goktug97** [comment]
## Remove 
# from
https://github.com/StrangerZhang/pyECO/blob/9179450159d8b4a5dd654d089af0cb5b75c70e9e/bin/demo_ECO_hc.py#L17
## to
https://github.com/StrangerZhang/pyECO/blob/9179450159d8b4a5dd654d089af0cb5b75c70e9e/bin/demo_ECO_hc.py#L20

# Add
```python
    cam = cv2.VideoCapture(video_dir)
    ret, frame = cam.read()
    bbox = cv2.selectROI(frame)
    frames = []
    while ret:
      frames.app    cam = cv2.VideoCapture(video_dir)
    ret, frame = cam.read()
    bbox = cv2.selectROI(frame)
    frames = []
    while ret:
      frames.append(frame)
      ret, frame = cam.read()
```

# remove these
https://github.com/StrangerZhang/pyECO/blob/9179450159d8b4a5dd654d089af0cb5b75c70e9e/bin/demo_ECO_hc.py#L27
https://github.com/StrangerZhang/pyECO/blob/9179450159d8b4a5dd654d089af0cb5b75c70e9e/bin/demo_ECO_hc.py#L40

## from
https://github.com/StrangerZhang/pyECO/blob/9179450159d8b4a5dd654d089af0cb5b75c70e9e/bin/demo_ECO_hc.py#L59
## to
https://github.com/StrangerZhang/pyECO/blob/9179450159d8b4a5dd654d089af0cb5b75c70e9e/bin/demo_ECO_hc.py#L61
