### ISSUE TITLE
ModuleNotFoundError: No module named 'eco' !!!

### ISSUE THREAD

**Issue by liuqinglong110** [StrangerZhang/pyECO#5]
When I run the commond "python bin/demo_ECO_hc.py --video_dir path/to/video",  print  ModuleNotFoundError: No module named 'eco' .     Could you help me ?

**Comment by StrangerZhang** [comment]
export PYTHONPATH=/path/to/pyECO:$PYTHONPATH should fix your problem

**Comment by liuqinglong110** [comment]
> export PYTHONPATH=/path/to/pyECO:$PYTHONPATH should fix your problem

Thank you very much for your reply！I have solved this problem.

The code "from eco import ECOTracker" in the demo_ECO_hc.py file should be changed to "from tracker import ECOTracker".

And in this line front, you need to add 
"import sys
Sys.path.append('../eco')"

Other errors can be solved in a similar way.

Now the program is working fine, thanks again！

**Comment by StrangerZhang** [comment]
That's not elegant, just export PYTHONPATH or sys.path.append('./') should fix your problem
