### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by whikwon** [StrangerZhang/pyECO#7]

**Comment by StrangerZhang** [comment]
Training is online, just run it.

**Comment by whikwon** [comment]
@StrangerZhang 
I'm sorry but I'm new to this field. 
Isn't there offline update stage in ECO? 

If not, how can normal DCF tracker's initial filter be updated?

**Comment by StrangerZhang** [comment]
Better to read the reference paper in README.md

No pretrained parameters used in ECO, all parameters is learned during online tracking

**Comment by whikwon** [comment]
OK, Thanks for help.
