### ISSUE TITLE
Speed is only 30 FPS on GTX1060

### ISSUE THREAD

**Issue by donggc** [StrangerZhang/pyECO#8]
The speed of ECO_HC is about 30fps on gtx1060,but,ECO_HC with C++ is 80fps on gtx1060. what's wrong ?

**Comment by StrangerZhang** [comment]
pyECO_HC not using GPU. The speed of pyECO_HC running on 8th intel i5 cpu is 40~60fps

**Comment by donggc** [comment]
23.8299369812
24.6319770813
24.1448879242
24.307012558
71.634054184
34.1138839722
31.9709777832
30.7259559631
31.0308933258
30.7738780975
73.9178657532
24.530172348
32.8969955444
29.3061733246
31.0289859772
31.3420295715
79.7970294952
32.438993454
以上是我检测的pyECO_HC跟踪每一帧的耗时情况，每六帧结果中会出现其中一帧耗时约70ms，其余耗时约30ms的情况。这是更新模型造成的吗？

**Comment by StrangerZhang** [comment]
是的，每6帧模型跟新一次
