### ISSUE TITLE
numpy数组颜色通道问题

### ISSUE THREAD

**Issue by fengyang95** [StrangerZhang/pyECO#9]
你好，我最近在练习一些想关滤波代码的python复现，参考了这个repo，很感谢！发现了一个小小的问题。
features.py中283行应改成
RR = patch[:, :, 2].astype(np.int32)
GG = patch[:, :, 1].astype(np.int32)
BB = patch[:, :, 0].astype(np.int32)

**Comment by StrangerZhang** [comment]
I use PIL to read image, so the image channel are RGB not BGR

**Comment by fengyang95** [comment]
Sorry, I thought you used the cv2 module.
